[package]
name = "bitcoin-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
varint = {package = "bitcoin-varint", version = "0.1.0"}

[dev-dependencies]
hex = "0.4.3"
